@startuml
class GUI_Simu <<partial>> {
    - components : System.ComponentModel.IContainer = null
    # <<override>> Dispose(disposing:bool) : void
    - InitializeComponent() : void
    - grpBSFRW : System.Windows.Forms.GroupBox
    - grpBProgramm : System.Windows.Forms.GroupBox
    - toolStrip1 : System.Windows.Forms.ToolStrip
    - btnStart : System.Windows.Forms.Button
    - btnStop : System.Windows.Forms.Button
    - btnReset : System.Windows.Forms.Button
    - btnStep : System.Windows.Forms.Button
    - grpBControls : System.Windows.Forms.GroupBox
    - lblWReg : System.Windows.Forms.Label
    - lblWRegVal : System.Windows.Forms.Label
    - lblPCL : System.Windows.Forms.Label
    - lblPCLVal : System.Windows.Forms.Label
    - lblPCLATH : System.Windows.Forms.Label
    - lblPCLATHVal : System.Windows.Forms.Label
    - lblPCLintern : System.Windows.Forms.Label
    - lblFSR : System.Windows.Forms.Label
    - lblPCLinternVal : System.Windows.Forms.Label
    - lblStatusVal : System.Windows.Forms.Label
    - lblStatus : System.Windows.Forms.Label
    - grBSFRBit : System.Windows.Forms.GroupBox
    - lblFSRVal : System.Windows.Forms.Label
    - lblOption : System.Windows.Forms.Label
    - lblVorteiler : System.Windows.Forms.Label
    - lblTimer0 : System.Windows.Forms.Label
    - lblOptionVal : System.Windows.Forms.Label
    - lblVorteilerVal : System.Windows.Forms.Label
    - lblTimer0Val : System.Windows.Forms.Label
    - lblRIFVal : System.Windows.Forms.Label
    - lblIntcon : System.Windows.Forms.Label
    - lblIFVal : System.Windows.Forms.Label
    - lblTIFVal : System.Windows.Forms.Label
    - lblGIE : System.Windows.Forms.Label
    - lblEIE : System.Windows.Forms.Label
    - lblRIEVal : System.Windows.Forms.Label
    - lblTIE : System.Windows.Forms.Label
    - lblIEVal : System.Windows.Forms.Label
    - lblIE : System.Windows.Forms.Label
    - lblTIEVal : System.Windows.Forms.Label
    - lblRIE : System.Windows.Forms.Label
    - lblEIEVal : System.Windows.Forms.Label
    - lblTIF : System.Windows.Forms.Label
    - lblGIEVal : System.Windows.Forms.Label
    - lblIF : System.Windows.Forms.Label
    - lblRIF : System.Windows.Forms.Label
    - lblPS0Val : System.Windows.Forms.Label
    - lblOpt : System.Windows.Forms.Label
    - lblPS1Val : System.Windows.Forms.Label
    - lblPS2Val : System.Windows.Forms.Label
    - lblRPu : System.Windows.Forms.Label
    - lblIEg : System.Windows.Forms.Label
    - lblPSAVal : System.Windows.Forms.Label
    - lblTCs : System.Windows.Forms.Label
    - lblTSeVal : System.Windows.Forms.Label
    - lblTSe : System.Windows.Forms.Label
    - lblTCsVal : System.Windows.Forms.Label
    - lblPSA : System.Windows.Forms.Label
    - lblIEgVal : System.Windows.Forms.Label
    - lblPS2 : System.Windows.Forms.Label
    - lblRPuVal : System.Windows.Forms.Label
    - lblPS1 : System.Windows.Forms.Label
    - lblPS0 : System.Windows.Forms.Label
    - lblCVal : System.Windows.Forms.Label
    - lblStatus2 : System.Windows.Forms.Label
    - lblDCVal : System.Windows.Forms.Label
    - lblZVal : System.Windows.Forms.Label
    - lblIRP : System.Windows.Forms.Label
    - lblRP1 : System.Windows.Forms.Label
    - lblPDVal : System.Windows.Forms.Label
    - lblRP0 : System.Windows.Forms.Label
    - lblTOVal : System.Windows.Forms.Label
    - lblTO : System.Windows.Forms.Label
    - lblRP0Val : System.Windows.Forms.Label
    - lblPD : System.Windows.Forms.Label
    - lblRP1Val : System.Windows.Forms.Label
    - lblZ : System.Windows.Forms.Label
    - lblIRPVal : System.Windows.Forms.Label
    - lblDC : System.Windows.Forms.Label
    - lblC : System.Windows.Forms.Label
    - tSDropDownDatei : System.Windows.Forms.ToolStripDropDownButton
    - dateiÖffnenToolStripMenuItem : System.Windows.Forms.ToolStripMenuItem
    - verlassenToolStripMenuItem : System.Windows.Forms.ToolStripMenuItem
    - tSDropDownEinstellungen : System.Windows.Forms.ToolStripDropDownButton
    - tSBtnHilfe : System.Windows.Forms.ToolStripButton
    - lVMemory : System.Windows.Forms.ListView
    - grpBMemory : System.Windows.Forms.GroupBox
    - grpBTiming : System.Windows.Forms.GroupBox
    - lblWdog : System.Windows.Forms.Label
    - chckBWatchdog : System.Windows.Forms.CheckBox
    - lblLaufztVal : System.Windows.Forms.Label
    - lblLaufzt : System.Windows.Forms.Label
    - lblWdogVal : System.Windows.Forms.Label
    - lblQuarz : System.Windows.Forms.Label
    - cmbBQuarz : System.Windows.Forms.ComboBox
    - tWorkingInterval : System.Windows.Forms.Timer
    - grpBPortA : System.Windows.Forms.GroupBox
    - lblPinA : System.Windows.Forms.Label
    - lblTrisA : System.Windows.Forms.Label
    - grpBPortB : System.Windows.Forms.GroupBox
    - chckBPortBTris0 : System.Windows.Forms.CheckBox
    - lblPinB : System.Windows.Forms.Label
    - lblTrisB : System.Windows.Forms.Label
    - chckBPortAPin4 : System.Windows.Forms.CheckBox
    - chckBPortAPin3 : System.Windows.Forms.CheckBox
    - chckBPortAPin2 : System.Windows.Forms.CheckBox
    - chckBPortAPin1 : System.Windows.Forms.CheckBox
    - chckBPortATris4 : System.Windows.Forms.CheckBox
    - chckBPortAPin0 : System.Windows.Forms.CheckBox
    - chckBPortATris0 : System.Windows.Forms.CheckBox
    - chckBPortATris3 : System.Windows.Forms.CheckBox
    - chckBPortATris1 : System.Windows.Forms.CheckBox
    - chckBPortATris2 : System.Windows.Forms.CheckBox
    - chckBPortBPin7 : System.Windows.Forms.CheckBox
    - chckBPortBPin6 : System.Windows.Forms.CheckBox
    - chckBPortBTris7 : System.Windows.Forms.CheckBox
    - chckBPortBPin5 : System.Windows.Forms.CheckBox
    - chckBPortBTris6 : System.Windows.Forms.CheckBox
    - chckBPortBPin4 : System.Windows.Forms.CheckBox
    - chckBPortBTris5 : System.Windows.Forms.CheckBox
    - chckBPortBPin3 : System.Windows.Forms.CheckBox
    - chckBPortBTris4 : System.Windows.Forms.CheckBox
    - chckBPortBPin2 : System.Windows.Forms.CheckBox
    - chckBPortBTris3 : System.Windows.Forms.CheckBox
    - chckBPortBPin1 : System.Windows.Forms.CheckBox
    - chckBPortBTris2 : System.Windows.Forms.CheckBox
    - chckBPortBPin0 : System.Windows.Forms.CheckBox
    - chckBPortBTris1 : System.Windows.Forms.CheckBox
    - lVProgram : System.Windows.Forms.ListView
    - grpBStack : System.Windows.Forms.GroupBox
    - lblStck1 : System.Windows.Forms.Label
    - lblStck2 : System.Windows.Forms.Label
    - lblStck3 : System.Windows.Forms.Label
    - lblStck4 : System.Windows.Forms.Label
    - lblStck5 : System.Windows.Forms.Label
    - lblStck6 : System.Windows.Forms.Label
    - lblStck7 : System.Windows.Forms.Label
    - lblStck0 : System.Windows.Forms.Label
}
@enduml
