@startuml
class InterruptController {
    + onRB0Changed(isFallingEdge:bool) : void
    + onRB4TO7Changed() : void
    + setInterruptFlag(flag:InterruptFlags) : void
    - isInterruptEnabled(bitAdress:int) : bool
    - decodeInterruptFlag(flag:InterruptFlags) : int
    + checkInterrupts() : void
}
enum InterruptFlags {
    T0IF,
    INTF,
    RBIF,
}
InterruptController +-- InterruptFlags
@enduml
