@startuml
class Parser {
    - filePath : string = "C:/tmp/testfile.txt"
    - rom : List<int>
    - totalFile : List<string>
    + setFilePath(newPath:string) : void
    + parse() : void
    + init() : void
    + getTotalFile() : List<string>
    + getRom() : List<int>
}
@enduml
