@startuml
class Prescaler {
    + getPrescaler() : int
    + getWDTPrescaler() : int
    + getTMR0Prescaler() : int
    - <<readonly>> prescalerTMR0 : Dictionary<int, int>
    - <<readonly>> prescalerWDT : Dictionary<int, int>
    - getOptionFile() : int
}
@enduml
