@startuml
class Decoder {
    - <<const>> sevenBitMask : int = 0x3f80
    - <<const>> sixBitMask : int = 0x3f00
    - <<const>> fiveBitMask : int = 0x3e00
    - <<const>> fourBitMask : int = 0x3c00
    - <<const>> threeBitMask : int = 0x3800
    - <<const>> clrwdtCommand : int = 0x64
    - <<const>> retfieCommand : int = 0x9
    - <<const>> returnCommand : int = 0x8
    - <<const>> sleepCommand : int = 0x63
    + Decoder()
    + decodeCommand(commandCode:int) : Command
    - isStaticCommand(commandCode:int) : CommandNames
    - extractFileAddress(commandCode:int) : int
    - extractBitAddress(commandCode:int) : int
    - extractJumpAddress(commandCode:int) : int
    - isResultWrittenToW(commandCode:int) : bool
    - extractLiteral(commandCode:int) : int
}
@enduml
