@startuml
class GUI_Simu <<partial>> {
    + {static} <<readonly>> parser : Parser
    + {static} <<readonly>> decoder : Decoder
    + {static} <<readonly>> executer : Executer
    + {static} <<readonly>> rom : ROM
    + {static} <<readonly>> memory : Memory
    + {static} <<readonly>> eeprom : EEPROM
    + {static} <<readonly>> controller : Controller
    + {static} <<readonly>> interruptController : InterruptController
    + {static} <<readonly>> prescaler : Prescaler
    + {static} <<readonly>> stack : Stack
    + {static} pcToLine : Dictionary<int, int>
    + {static} lineToPc : Dictionary<int, int>
    helpMsg : string
    + GUI_Simu()
    - GUI_Simu_load(sender:object, e:EventArgs) : void
    - GUI_Simu_close(sender:object, e:FormClosingEventArgs) : void
    + reset() : void
    + init() : void
    + refresh() : void
    + memAdrRes_setFile(fileAddress:int, value:int) : int
    + memAdrRes_getFile(fileAddress:int) : int
    + memAdrRes_getBit(fileAddress:int, bitAddress:int) : int
    + memAdrRes_setBit(fileAddress:int, bitAddress:int) : void
    + memAdrRes_clearBit(fileAddress:int, bit:int) : void
    + memAdrRes_requestAccess(fileAddress:int, bit:int) : bool
    + refreshStack() : void
    + refreshIO() : void
    - PortAPin0(sender:object, e:EventArgs) : void
    - PortAPin1(sender:object, e:EventArgs) : void
    - PortAPin2(sender:object, e:EventArgs) : void
    - PortAPin3(sender:object, e:EventArgs) : void
    - PortAPin4(sender:object, e:EventArgs) : void
    - PortBPin0(sender:object, e:EventArgs) : void
    - PortBPin1(sender:object, e:EventArgs) : void
    - PortBPin2(sender:object, e:EventArgs) : void
    - PortBPin3(sender:object, e:EventArgs) : void
    - PortBPin4(sender:object, e:EventArgs) : void
    - PortBPin5(sender:object, e:EventArgs) : void
    - PortBPin6(sender:object, e:EventArgs) : void
    - PortBPin7(sender:object, e:EventArgs) : void
    - refreshSFR_b() : void
    + refreshSFRW() : void
    + initMemory() : void
    + refreshMemory() : void
    + resetTiming() : void
    + setLaufzeit(val:int) : void
    + enableButtons() : void
    + disableButtons() : void
    - btnStart_Click(sender:object, e:EventArgs) : void
    - btnStop_Click(sender:object, e:EventArgs) : void
    - btnReset_Click(sender:object, e:EventArgs) : void
    - btnStep_Click(sender:object, e:EventArgs) : void
    - itemChecked(sender:object, e:ItemCheckedEventArgs) : void
    + {static} getDictPcToLine(newdict:Dictionary<int, int>) : void
    + {static} getDictLineToPc(newdict:Dictionary<int, int>) : void
    + showFile(file:List<string>) : void
    + selectLine() : void
    + setBreakPoint() : void
    - verlassenToolStripMenuItem_Click(sender:object, e:EventArgs) : void
    - dateiÖffnenToolStripMenuItem_Click(sender:object, e:EventArgs) : void
    - tSBtnHilfe_Click(sender:object, e:EventArgs) : void
    - tWorkingInterval_Tick(sender:object, e:EventArgs) : void
    + stopTimer() : void
    + startTimer() : void
    + controllerStep() : void
}
Form <|-- GUI_Simu
@enduml
